### PR TITLE
Further little improvements

### PR DESCRIPTION
**Pull request by cincodenada**
A couple more visual improvements (center the earth, and round the corners)

And some JS style improvements while I was at it - just use a JSON array instead of assigning elements individually (takes care of the JSHint warning, nice check there!), and move the one-time stuff (creating the array and sorting it) out of the countryUpdate loop.

The last line of the JS wasn't working and throwing an error, because the JS runs before the document is loaded, so when that code ran the retrybutton element didn't exist yet.  The onclick="" attribute on the element was already there and works fine, so I just took the line out of the JS.

### CODE REVIEW

**Comment by cincodenada** [comment]
Heyo, here are the other improvements I'd made.  Solid work on your part, all the JS stuff is just minor style cleanup that you can take or leave.  I just have instincts from doing frontend Javascript stuff for far too long :)

**Comment by wackywendell** [comment]
Looks great, thanks! I'm not really a web-dev usually, so thanks for cleaning up the HTML and Javascript; I appreciate it!

Could you rebase on master, and then I'll merge?

**Comment by cincodenada** [comment]
This one (patch-2) should be rebased on master (gh-pages, actually) already, unless I'm missing something.  And yeah, checking out your projects, it seemed like you're usually more of a backend/desktop/hardware guy.  Glad I could help :)

**Comment by wackywendell** [comment]
Ah! You're right; I got confused by your `patch-1` branch, which is now both behind and ahead. Thanks again!

**Pull request merged**
